### ISSUE TITLE
NEWLINE defaults to windows CRLF also on *nix systems...

### ISSUE THREAD

**Issue by Knusper** [makeworld-the-better-one/md2gemini#29]
Right now `NEWLINE` is hardcoded to windows `\r\n` (carriage return & line feed) whereas under *nix systems just `\n` (line feed) is enough.  The gemini protocol works fine with just line feeds, and the clients have to understand this, regardless of operating system.  Can this be done a bit more elegantly, i.e. depending on the users system?

**Comment by makeworld-the-better-one** [comment]
I'm not really interested in md2gemini working differently on different OSes, that seems like an unexpected behaviour to me. I went with `\r\n` because I know it will work fine on all OSes and editors, and isn't really an issue in other situations.

In any case, you should be able to change this behaviour by changing the `md2gemini.NEWLINE` variable. Let me know if that doesn't work for you. I could also add a command line flag if you need.

**Comment by Knusper** [comment]
If I would not have I noticed when parsing he output files on linux I
wouldn't have opened the bug.  Your assumption about how users may process
their files is not correct. If I use a command in *nix, I expect that I
don't need to pipe the output to dos2unix to further process them.

The fix is trivial (sys.platform). Are you really not interested? I could
file a PR.

**Comment by makeworld-the-better-one** [comment]
I didn't realize these line endings could cause a parsing issue, what were you trying to do? I could make this change, I was just wary of having different outputs on different OSes. Again, would a CLI flag not work?
